name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - uses: actions/checkout@v3
    - name: Install
      run: pnpm install
    - name: Build
      run: pnpm build
      
